function dt_comparison(X1, YMatrix1, X2, YMatrix2, X3, YMatrix3)
%CREATEFIGURE(X1,YMATRIX1,X2,YMATRIX2,X3,YMATRIX3)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data
%  X2:  vector of x data
%  YMATRIX2:  matrix of y data
%  X3:  vector of x data
%  YMATRIX3:  matrix of y data

%  Auto-generated by MATLAB on 15-Oct-2010 18:45:07

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 4.5]);
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',axes1,'Color',[1 0 0]);
set(plot1(1),'DisplayName','10^{-3}');

% Create multiple lines using matrix input to plot
plot2 = plot(X2,YMatrix2,'Parent',axes1,'Color',[0 0 1]);
set(plot2(1),'DisplayName','5\times10^{-4}');

% Create multiple lines using matrix input to plot
plot3 = plot(X3,YMatrix3,'Parent',axes1,'Color',[0 0 0]);
set(plot3(1),'DisplayName','2.5\times10^{-4}');

% Create xlabel
xlabel('t [ps]');

% Create ylabel
ylabel('x, y, x  [A]');

% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Location','SouthWest');

