#!/bin/bash

for f in $@; do
    if [ ! -f "$f" ]; then
        continue
    fi
    obj=${f%.*}.o
    mods=$(sed -n -e "/^[[:space:]]*module[[:space:]]/s/[[:space:]]*module[[:space:]]//gp" "$f")
    if [ x"$mods" != x ]; then
        for m in $mods; do
            echo "$m.mod: $obj"
        done
    fi

    deps=""
    used=$(sed -n -e "/^[[:space:]]*use[[:space:]]/s/use//p" "$f" | sort -u)
    if [ x"$used" != x ]; then
        for u in $used; do
            deps="$deps $u.mod"
        done
    fi

    includes=$(sed -n -e "/^[[:space:]]*include[[:space:]]/s/include//gp" "$f" | sed "s/\'//gp" | sort -u)
    if [ x"$includes" != x ]; then
        for f in $includes; do
            deps="$deps $f"
        done
    fi
    if [ x"$deps" != x ]; then
        echo "$obj: $deps"
    fi

done


