set(CMAKE_C_COMPILER icc)
set(CMAKE_Fortran_COMPILER ifort)
enable_language(C)
enable_language(Fortran)
set(OPTFLAGS "-O3 -mdynamic-no-pic -no-prec-div")
set(CMAKE_C_FLAGS_RELEASE ${OPTFLAGS})
set(CMAKE_C_FLAGS_DEBUG "-O0 -g")
set(CMAKE_Fortran_FLAGS_RELEASE ${OPTFLAGS} "-r8 -heap-arrays")
set(CMAKE_Fortran_FLAGS_DEBUG "-O0 -g -r8 -heap-arrays -check bounds -traceback -warn all")
set(LINKFLAGS -nofor-main)
find_library(LAPACK Intel_MKL)
#find_library(LAPACK NAMES mkl_sequential PATHS $ENV{MKLROOT}/lib/em64t)
#find_library(LAPACK NAMES mkl_core PATHS $ENV{MKLROOT}/lib/em64t)


